site_name: コンテンツインタラクション演習
theme: readthedocs
nav:
  - Home: index.md
  - 環境構築: setup/README.md
  - 2D 線・円:
    - 直線: lines/README.md
    - 円: circle/README.md
  - 2D 相対移動: surface/README.md
  - 3D 階層構造: box/README.md
  - アニメーション: animation/README.md
  - マウスやキーボードによる入力: input/README.md
  - ワンクリックアクションの制作: oneclick/README.md
  - タイミングアクション: timing/README.md
  - 軌跡を用いたインタラクション: trace/README.md
